### ISSUE TITLE
"email" format validation rejects valid e-mail addresses

### ISSUE THREAD

**Issue by daehlith** [Prestaul/skeemas#1]
The regular expression used by skeemas to validate strings with the "email" format attribute reject various valid e-mail address if the top-level domain suffix exceeds 4 characters. While those suffixes are rare, they do exist, and as such this case should be handled correctly.

An example of a valid e-mail address that currently fails validation would be `contact@louvre.museum`

**Comment by Prestaul** [comment]
@daehlith, I knew [this issue](http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address) was going to come up at some point. :stuck_out_tongue: 

I had to choose between being very liberal and ensuring that I accepted all possible email addresses including some that were invalid, or being more selective and possibly excluding some valid (but almost never seen) email addresses. As mentioned [here](http://www.regular-expressions.info/email.html), I could match `.museum` but

> This regex will match john@mail.office. It's far more likely that John forgot to type in the .com top level domain rather than having just created a new .office top level domain...

Maybe I should have gone for the more liberal regular expression... Maybe I should just allow any TLD over 2 chars long? What do you think?

**Comment by daehlith** [comment]
If it is necessary to verify the correctness of an e-mail address than that cannot be achieved using a syntactical validation of said e-mail address. As such I'd suggest to simply accept everything that looks like a syntactically valid e-mail address as per RFC 5322, and delegate the responsibility of verification to a different level than the JSON schema validation.

**Comment by Prestaul** [comment]
@daehlith, thanks for the report and the feedback. I've published a much more liberal version of the email validation in version 1.2.0
